---
# file: tasks/main.yml
# Top-level installer for Nginx.
#
# @see http://wiki.nginx.org/Install

- name: install the latest version of nginx
  yum:
    name: nginx
    state: latest
  become: true

- name: Copy nginx.repo configuration for nginx
  copy:
    src: nginx.repo 
    dest: /etc/yum.repos.d/
  become: true

- name: Ensure directory /etc/nginx/conf.d/ exists.
  file:
    path: /etc/nginx/conf.d/
    state: directory

- name: Copy kibana.conf configuration for nginx /etc/nginx/conf.d/
  copy:
    src: kibana.conf
    dest: /etc/nginx/conf.d/
  become: true

- name: Copy nginx.conf to /etc/nginx/
  copy:
    src: nginx.conf
    dest: /etc/nginx/
  become: true

- name: Enable service nginx
  service:
    name: nginx
    enabled: yes
  become: true

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

#force all handlers to run - so all db updates will take effect  
- meta: flush_handlers

